[package]
name = "pdf"
version = "0.1.0"
edition = "2021"


[dependencies]
font_data = { path = "../font-data/" }
cairo-rs = { git = "https://github.com/gtk-rs/gtk-rs-core.git", features = [
  "freetype",
  "png",
] }
encoding_rs = "0.8.33"
env_logger = "0.10.1"
flate2 = "1.0.28"
freetype-rs = "0.37.0"
image = "0.25.1"
imageproc = "0.24.0"
lazy_static = "1.4.0"
log = "0.4.20"
rand = "0.8.5"
thiserror = "1.0.51"
bitstream-io = "2.3.0"
fax = "0.2.4"
mozjpeg = "0.10.8"
